### ISSUE TITLE
unable to import using Typescript. Using node it is ok

### ISSUE THREAD

**Issue by str3tch** [node-casbin/express-authz#11]
hi there,

I have installed the package and I can see it in my project's node_modules folder.

However, if I try to import the typescript way it cannot find the module:
```javascript
import { authz } from 'casbin-express-authz';
```

If I use the old NodeJS way, using require, it can find the module:
```javascript
var cas = require('casbin-express-authz');
```

See here, both methods are below. The TS version has an issue.
![image](https://user-images.githubusercontent.com/1896276/80773351-3808bb00-8b8c-11ea-83e2-15c81a67f15b.png)

And reports this error on building:
![image](https://user-images.githubusercontent.com/1896276/80773437-80c07400-8b8c-11ea-8c45-4fb0cb691897.png)

From a little googling, perhaps express-authz is missing a types file?

**Comment by nodece** [comment]
Thanks @str3tch ,  `v3.0.1` has been released.
