### ISSUE TITLE
Fix the CI error for Node.js: stable

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/express-authz#13]
https://travis-ci.com/github/node-casbin/express-authz/builds/216995952

![image](https://user-images.githubusercontent.com/3787410/107840788-b3bcb700-6df0-11eb-90d1-db33c2ec9f07.png)

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
got it

**Comment by hsluoyz** [comment]
@17bit I think we can change to GitHub Actions directly.

**Comment by hsluoyz** [comment]
Fixed by commit: https://github.com/node-casbin/express-authz/commit/09eef66794fd252fa56d727e44cfa55b8fc1820e
