### ISSUE TITLE
Dependencies look unrelated to runtime usage

### ISSUE THREAD

**Issue by zillding** [node-casbin/express-authz#15]
Just wondering if the `dependencies` (like `husky` etc) are used during runtime of this package. These will be force installed when installing this package and affect the dev experience.

**Comment by hsluoyz** [comment]
@tangyang9464 @Gabriel-403 @MRGUOKING

**Comment by Gabriel-403** [comment]
yes，these will be force installed when installing this package，because npm will automatic install them  according to package.json

**Comment by MRGUOKING** [comment]
@zillding Yes. When you use "npm install casbin " or "yarn add casbin". The all dependencies appeared in the package.json will be force installed.

**Comment by zillding** [comment]
Thanks for the reply. From the source code: https://github.com/node-casbin/express-authz/blob/master/src/authz.ts, the only dependencies look to be `casbin` and `express`.

Should this package be similar to https://github.com/node-casbin/koa-authz in terms of dependencies?

**Comment by hsluoyz** [comment]
@nodece @Zxilly
